#####################################
# Deployment Pipeline for Dummy API #
#####################################
#
# NOTE: This example uses the build-once-deploy-many pattern
# Package is built ONCE and the SAME package is deployed to all environments
# For details, see: ci-templates/azuredevops/docs/BUILD_ONCE_PATTERN.md
#

parameters:
  - name: packageVersion
    displayName: Package Version, leave 0 for a new deployment OR put the Build Number to reuse an existing package. For instance put dummy-api.20230111.1.BUILD
    type: string
    default: 0
  - name: notes
    displayName: Notes
    type: string
    default: "Dummy API Bundle"
  - name: deployToQA
    displayName: Deploy to QA
    type: boolean
    default: true
  - name: deployToUAT
    displayName: Deploy to UAT
    type: boolean
    default: false
  - name: deployToProd
    displayName: Deploy to Production
    type: boolean
    default: false
  - name: branchName
    displayName: Branch Name
    type: string
    default: "main"

trigger:
  - main

pool:
  name: Default
  demands:
    - agent.os -equals Linux

extends:
  template: /ci-templates/azuredevops/pipelines/base_build_approval_deploy.yaml
  parameters:
    packageVersion: ${{ parameters.packageVersion }}
    packageName: "dummy-api"
    componentIds: "dd185596-c539-4d31-97c5-1a46f13eafa4,8d4bd7c8-1071-4ba9-a697-8e5e21a6e229,2dcfe4f6-0a27-4ad3-afa8-67a873b1edd1"
    test_componentIds: "590ed42b-a6b5-4c73-a8f8-5dc2451514b7"
    notes: ${{ parameters.notes }}
    deployToQA: ${{ parameters.deployToQA }}
    deployToUAT: ${{ parameters.deployToUAT }}
    deployToProd: ${{ parameters.deployToProd }}
    postmanCollection: "dummy-api-basic-postman.json"
    sleepInMinutes: 1
    branchName: ${{ parameters.branchName }}
